### ISSUE TITLE
Error loading state_dict for Pidinet

### ISSUE THREAD

**Issue by mike-silver-Crafty-Apes-VFX** [zhuoinoulu/pidinet#50]
Getting the following error when running the following command. Possibly the model and the weights are a mismatch?

python main.py --model pidinet_converted --config carv4 --sa --dil -j 4 --gpu 0 --savedir output --datadir input_images --dataset Custom --evaluate trained_models/table5_pidinet.pth --evaluate-converted

Traceback (most recent call last):
  File "C:\Users\Mike\Desktop\Coding\pidinet\pidinet-master\pidinet-master\main.py", line 419, in <module>
    main(f)
  File "C:\Users\Mike\Desktop\Coding\pidinet\pidinet-master\pidinet-master\main.py", line 202, in main
    model.load_state_dict(convert_pidinet(checkpoint['state_dict'], args.config))
  File "C:\Users\Mike\Anaconda3\envs\pidinet\Lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PiDiNet:

**Comment by PrasannaKumar29** [comment]
Hi. Did u fix the issue? I'm facing the same

**Comment by TIAcode** [comment]
I get this error if I leave `--gpu 0` argument out, with GPU it works.
