### ISSUE TITLE
Checkpoints file and table5_pidinet model

### ISSUE THREAD

**Issue by emmmmmmmer** [zhuoinoulu/pidinet#6]
Hello, where can I download the checkpoints file? I want to train a table5_pidinet model, but I have encountered some difficulties. Is it convenient for email to contact?

**Comment by emmmmmmmer** [comment]
Namespace(ablation=False, checkinfo=False, config='carv4', datadir='/home/lu/pidinet-master/data/BSDS500/', dataset=['BSDS'], dil=True, epochs=20, eta=0.3, evaluate=None, evaluate_converted=False, gpu='0', iter_size=24, lmbda=1.1, lr=0.005, lr_steps=[10, 16], lr_type='multistep', model='pidinet', only_bsds=False, opt='adam', print_freq=10, resume=True, sa=True, save_freq=1, savedir='/home/lu/pidinet-master/table5_pidinet/', seed=1631092025, use_cuda=True, wd=0.0001, workers=4)
{'layer0': 'cd', 'layer1': 'ad', 'layer2': 'rd', 'layer3': 'cv', 'layer4': 'cd', 'layer5': 'ad', 'layer6': 'rd', 'layer7': 'cv', 'layer8': 'cd', 'layer9': 'ad', 'layer10': 'rd', 'layer11': 'cv', 'layer12': 'cd', 'layer13': 'ad', 'layer14': 'rd', 'layer15': 'cv'}
initialization done
conv weights: lr 0.005000, wd 0.000100  bn weights: lr 0.005000, wd 0.000010    relu weights: lr 0.005000, wd 0.000000
cuda is used, with 1 gpu devices
Threshold for ground truth: 76.800000 on BSDS_VOC
Threshold for ground truth: 76.800000 on BSDS_VOC
=> loading checkpoint from ''
no checkpoint loaded
Traceback (most recent call last):
  File "main.py", line 418, in <module>
    main(f)
  File "main.py", line 229, in main
    train_loader, model, optimizer, epoch, running_file, args, lr_str)
  File "main.py", line 264, in train
    for i, (image, label) in enumerate(train_loader):
  File "/home/lu/anaconda3/envs/python37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/lu/anaconda3/envs/python37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/lu/anaconda3/envs/python37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/lu/anaconda3/envs/python37/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lu/anaconda3/envs/python37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lu/anaconda3/envs/python37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lu/anaconda3/envs/python37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lu/pidinet-master/edge_dataloader.py", line 117, in __getitem__
    lb = np.array(Image.open(os.path.join(self.root, lb_file)), dtype=np.float32)
  File "/home/lu/anaconda3/envs/python37/lib/python3.7/site-packages/PIL/Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/lu/pidinet-master/data/BSDS500/HED-BSDS/train/aug_gt_scale_0.5/315.0_1_0/55073.png'

**Comment by emmmmmmmer** [comment]
python main.py --model pidinet --config carv4 --sa --dil --resume --iter-size 24 -j 4 --gpu 0 --epochs 20 --lr 0.005 --lr-type multistep --lr-steps 10-16 --wd 1e-4 --savedir /home/lu/pidinet-master/table5_pidinet/ --datadir /home/lu/pidinet-master/data/BSDS500/ --dataset BSDS

**Comment by zhuoinoulu** [comment]
> python main.py --model pidinet --config carv4 --sa --dil --resume --iter-size 24 -j 4 --gpu 0 --epochs 20 --lr 0.005 --lr-type multistep --lr-steps 10-16 --wd 1e-4 --savedir /home/lu/pidinet-master/table5_pidinet/ --datadir /home/lu/pidinet-master/data/BSDS500/ --dataset BSDS

The checkpoint files are in the google drive and can be downloaded by clicking the model names in the README table. Let me know if there are any question for downloading that. 

The error seems like to show the png files of the dataset are not found. Could you please check your png files if they are put in the path correctly?

**Comment by emmmmmmmer** [comment]
Thanks for your answer, I have solved this problem

**Comment by Muqing7783** [comment]
> 

how to solve?
